version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Run tests and upload to Codecov
          command: yarn test
      - store_test_results:
          path: test/unit

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build the project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .
workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test
